### ISSUE TITLE
Gradle build in .travis

### ISSUE THREAD

**Issue by tgsmith61591** [charlesdrotar/alkaline#2]
Can't define two languages in `.travis.yml`, so I'll have to get a bit clever in how we build and conduct the Java test suite prior to the actual python tests.

**Comment by charlesdrotar** [comment]
Call me crazy but what if we built the Python with Travis and the Java with something like Circle. We could maintain individuality between the languages given that they would have separate .yml files. That would be my solution. Plus it wouldn't be too hacky it would just require us to become more fluent with Circle...which is an inevitability anyway :wink:. 

Now that I think about it the problem arises that the Java has to be tested then compiled to be consequently used within the Python code. Maybe the solution is looking into another CI tool that handles this natively. If such thing doesn't exist I am open for hacking something together.

Unless you have a good reason why this wouldn't be okay. I am open for suggestions.

What do you think?

**Comment by charlesdrotar** [comment]
Also looked at calling gradle from within Travis during the build step [here](https://docs.travis-ci.com/user/languages/java/#Projects-Using-Gradle).

Not sure if you could call that then call the python tests in succession.

**Comment by tgsmith61591** [comment]
It all needs to be in one CI build, as alkaline depends on its java build
(or will, rather). I added a `./gradlew build` statement in the
.travis.yml. Will test..

**Comment by tgsmith61591** [comment]
I think we're going to have to make it a java project in the `.travis.yml` for it to automagically build/test the gradle project, then we can call the test script to test the python code. That might be the best way to do this 😸 In order to test locally, it would just be:

```bash
$ ./gradlew test
$ nosetests
```

**Comment by tgsmith61591** [comment]
#1 is passing now, so I'm closing this issue out. Please merge the PR
